### ISSUE TITLE
Year option base on max date

### ISSUE THREAD

**Issue by ksromero** [qodesmith/datepicker#59]
Is it possible to have a year option that shows all of the year base on the max date?

**Comment by qodesmith** [comment]
Were you looking to show _only_ the months in the overlay like this?
<img width="447" alt="Screen Shot 2019-08-04 at 6 54 19 AM" src="https://user-images.githubusercontent.com/11034792/62422722-fdb5d000-b684-11e9-8a5e-02b8b4f6d890.png">

If that's the case, you can achieve that by adding these custom styles to your stylesheet:
```css
.qs-overlay-year {
  visibility: hidden;
}

.qs-submit {
  display: none;
}
```
